# CycleSense

# Notebook 04: Feature Engineering

## Objective

This notebook prepares task-specific datasets for machine learning.

The preprocessing performed here includes:

- Removing identifier variables
- Selecting target variables
- Creating feature matrices for each prediction task
- Saving task-specific datasets

Categorical encoding and feature scaling will be performed inside machine learning pipelines during model training to prevent data leakage.

In [1]:
import warnings
warnings.filterwarnings("ignore")

In [2]:
import numpy as np
import pandas as pd

In [3]:
from sklearn.preprocessing import LabelEncoder

In [4]:
from src.config import PROCESSED_DATA_DIR

In [5]:
df = pd.read_csv(
    PROCESSED_DATA_DIR / "cleaned_cycle_data.csv"
)

print(df.shape)

df.head()

(1653, 80)

,ClientID,CycleNumber,Group,CycleWithPeakorNot,ReproductiveCategory,LengthofCycle,MeanCycleLength,EstimatedDayofOvulation,LengthofLutealPhase,FirstDayofHigh,...,Method,Prevmethod,Methoddate,Whychart,Nextpreg,NextpregM,Spousesame,SpousesameM,Timeattemptpreg,BMI
0,nfp8122,1,0,1,0,29,27.33,17.0,12.0,12.0,...,9.0,2.0,32009,2.0,7.0,7.0,1.0,1.0,0.0,21.254724
1,nfp8122,2,0,1,0,27,29.50,15.0,12.0,13.0,...,9.0,2.0,32009,3.0,3.0,3.0,1.0,1.0,0.0,24.114742
2,nfp8122,3,0,1,0,29,29.50,15.0,14.0,11.0,...,9.0,2.0,32009,3.0,3.0,3.0,1.0,1.0,0.0,24.114742
3,nfp8122,4,0,1,0,27,29.50,15.0,12.0,13.0,...,9.0,2.0,32009,3.0,3.0,3.0,1.0,1.0,0.0,24.114742
4,nfp8122,5,0,1,0,28,29.50,16.0,12.0,12.0,...,9.0,2.0,32009,3.0,3.0,3.0,1.0,1.0,0.0,24.114742

## Remove Identifier Columns

Identifiers do not contribute to prediction and may cause overfitting.

In [7]:
identifier_columns = [
    "ClientID",
    "CycleNumber"
]

identifier_columns = [
    col for col in identifier_columns
    if col in df.columns
]

df = df.drop(columns=identifier_columns)

print(df.shape)

(1653, 78)

In [18]:
print(df.dtypes.value_counts())

float64    68
int64      10
Name: count, dtype: int64

## Encode Variables

Machine learning models require numerical input.

In [28]:
categorical_features = df.select_dtypes(include="object").columns.tolist()

numerical_features = df.select_dtypes(exclude="object").columns.tolist()

print("Categorical:", len(categorical_features))
print("Numerical :", len(numerical_features))

Categorical: 0
Numerical : 78

# Remove Potential Leakage Features

In [ ]:
leakage_features = [

    "FirstDayofHigh",

    "TotalNumberofHighDays",

    "TotalHighPostPeak",

    "TotalNumberofPeakDays",

    "TotalDaysofFertility",

    "TotalFertilityFormula"

]

df = df.drop(columns=leakage_features)

df.shape

# Dataset 1

## Predict Estimated Day of Ovulation

In [20]:
target = "EstimatedDayofOvulation"

X_ovulation = df.drop(columns=[target])

y_ovulation = df[target]

print(X_ovulation.shape)

(1653, 77)

# Dataset 2

## Predict Cycle Length

In [21]:
target = "LengthofCycle"

X_cycle = df.drop(columns=[target])

y_cycle = df[target]

print(X_cycle.shape)

(1653, 77)

# Dataset 3

## Predict Cycle With Peak or Not

In [22]:
target = "CycleWithPeakorNot"

X_peak = df.drop(columns=[target])

y_peak = df[target]

print(X_peak.shape)

(1653, 77)

In [23]:
print(X_ovulation.columns.tolist())

['Group', 'CycleWithPeakorNot', 'ReproductiveCategory', 'LengthofCycle', 'MeanCycleLength', 'LengthofLutealPhase', 'FirstDayofHigh', 'TotalNumberofHighDays', 'TotalHighPostPeak', 'TotalNumberofPeakDays', 'TotalDaysofFertility', 'TotalFertilityFormula', 'LengthofMenses', 'MeanMensesLength', 'MensesScoreDayOne', 'MensesScoreDayTwo', 'MensesScoreDayThree', 'MensesScoreDayFour', 'MensesScoreDayFive', 'MensesScoreDaySix', 'MensesScoreDaySeven', 'MensesScoreDayEight', 'MensesScoreDayNine', 'MensesScoreDayTen', 'MensesScoreDay11', 'MensesScoreDay12', 'MensesScoreDay13', 'MensesScoreDay14', 'MensesScoreDay15', 'TotalMensesScore', 'MeanBleedingIntensity', 'NumberofDaysofIntercourse', 'IntercourseInFertileWindow', 'UnusualBleeding', 'PhasesBleeding', 'IntercourseDuringUnusBleed', 'Age', 'AgeM', 'Maristatus', 'MaristatusM', 'Yearsmarried', 'Wedding', 'Religion', 'ReligionM', 'Ethnicity', 'EthnicityM', 'Schoolyears', 'SchoolyearsM', 'OccupationM', 'IncomeM', 'Height', 'Weight', 'Reprocate', 'Numberpreg', 'Livingkids', 'Miscarriages', 'Abortions', 'Medvits', 'Medvitexplain', 'Gynosurgeries', 'LivingkidsM', 'Boys', 'Girls', 'MedvitsM', 'MedvitexplainM', 'Urosurgeries', 'Breastfeeding', 'Method', 'Prevmethod', 'Methoddate', 'Whychart', 'Nextpreg', 'NextpregM', 'Spousesame', 'SpousesameM', 'Timeattemptpreg', 'BMI']

# Feature Summary

In [24]:
summary = pd.DataFrame({

    "Dataset":[
        "Ovulation",
        "Cycle Length",
        "Peak Detection"
    ],

    "Features":[
        X_ovulation.shape[1],
        X_cycle.shape[1],
        X_peak.shape[1]
    ],

    "Samples":[
        X_ovulation.shape[0],
        X_cycle.shape[0],
        X_peak.shape[0]
    ]

})

summary

          Dataset  Features  Samples
0       Ovulation        77     1653
1    Cycle Length        77     1653
2  Peak Detection        77     1653

In [25]:
summary.to_csv(
    PROCESSED_DATA_DIR / "dataset_summary.csv",
    index=False
)

In [26]:
X_ovulation.to_csv(
    PROCESSED_DATA_DIR / "X_ovulation.csv",
    index=False
)

y_ovulation.to_csv(
    PROCESSED_DATA_DIR / "y_ovulation.csv",
    index=False
)

X_cycle.to_csv(
    PROCESSED_DATA_DIR / "X_cycle.csv",
    index=False
)

y_cycle.to_csv(
    PROCESSED_DATA_DIR / "y_cycle.csv",
    index=False
)

X_peak.to_csv(
    PROCESSED_DATA_DIR / "X_peak.csv",
    index=False
)

y_peak.to_csv(
    PROCESSED_DATA_DIR / "y_peak.csv",
    index=False
)

print("Datasets saved successfully.")

Datasets saved successfully.

# Conclusion

Three task-specific datasets have been created for:

- Ovulation Day Prediction (Regression)
- Cycle Length Prediction (Regression)
- Peak Detection (Classification)

Categorical encoding, scaling, imputation, and model training will be performed using scikit-learn Pipelines in the subsequent notebooks. This approach prevents data leakage and ensures that preprocessing learned from the training set is consistently applied to validation and test data.